import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "sonner";
import { unstable_setRequestLocale } from "next-intl/server";
import { NextIntlClientProvider, useMessages } from "next-intl";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  unstable_setRequestLocale(locale);
  const msg = useMessages();

  return (
    <html lang={locale}>
      <Toaster />
      <body className={`${inter.className}`}>
        <NextIntlClientProvider locale={locale} messages={msg}>
          <Navbar />
          <div className="">{children}</div>
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
